CREATE SEQUENCE user_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE pauta_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE sessao_votacao_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE voto_id_seq START WITH 1 INCREMENT BY 1;